//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColourChanger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColourChanger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ColourFilter&gt;
        ///	&lt;Data&gt;
        ///		&lt;name&gt;Reset&lt;/name&gt;
        ///		&lt;RedByte_RedScalling&gt;1&lt;/RedByte_RedScalling&gt;
        ///		&lt;RedByte_GreenScalling&gt;0&lt;/RedByte_GreenScalling&gt;
        ///		&lt;RedByte_BlueScalling&gt;0&lt;/RedByte_BlueScalling&gt;
        ///		&lt;RedByte_AlphaScalling&gt;0&lt;/RedByte_AlphaScalling&gt;
        ///		&lt;RedByte_ColourCast&gt;0&lt;/RedByte_ColourCast&gt;
        ///
        ///		&lt;GreenByte_RedScalling&gt;0&lt;/GreenByte_RedScalling&gt;
        ///		&lt;GreenByte_GreenScalling&gt;1&lt;/GreenByte_GreenScalling&gt;
        ///		&lt;GreenByte_BlueScalling&gt;0&lt;/GreenByte_BlueScalling&gt;
        ///		&lt;GreenByte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ColourFilterData {
            get {
                return ResourceManager.GetString("ColourFilterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Help1 {
            get {
                object obj = ResourceManager.GetObject("Help1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
